dimens & style
ndv6/tsaving-mobile pull request #21
Opened 2020-07-29 14:49 UTC by jocelyntjahyadi

2020-07-29 14:55 UTC, sekarminati approved these changes

2020-07-29 15:05 UTC, david1312 requested changes

2020-07-29 15:05 UTC, david1312 commented on app/src/main/res/layout/activity_add_va.xml
> +<!--    <androidx.appcompat.widget.Toolbar-->
maybe can delete this if not used

2020-07-31 09:21 UTC, david1312 approved these changes
good to go

2020-08-01 11:23 UTC, merged