Ui/dashboard
ndv6/tsaving-mobile pull request #46
Opened 2020-08-02 17:13 UTC by polipopoliko

Adding search and sort feature

2020-08-02 17:18 UTC, polipopoliko commented
Btw terkait log yang di bagian search gw ga mau hapus ya, thank you.

2020-08-02 17:22 UTC, david1312 requested changes

2020-08-02 17:22 UTC, david1312 commented on app/src/main/java/com/example/tsaving/DashboardSearchFragment.kt
> +                    tv_dashboard_search_va_balance.text = vaMap[sub]?.vaBalance.toString() ?: "0"
can give thousand separator using FormatDecimal() from extensions class

2020-08-03 02:45 UTC, vicimilenia approved these changes

2020-08-03 03:11 UTC, yulyulyharuka approved these changes

2020-08-03 04:42 UTC, david1312 approved these changes

2020-08-03 04:46 UTC, closed without merging